import React, { useState, useMemo } from 'react';
import { 
  ChevronDown, 
  ChevronRight, 
  FileText, 
  Search, 
  Plus, 
  Eye, 
  CheckCircle2, 
  RefreshCw,
  Save,
  Info,
  Pencil,
  Check,
  X
} from 'lucide-react';
import { MOCK_DATA, INCOME_DATA, PROFORMA_COLUMNS, INCOME_COLUMNS, FinancialRow, YearColumn } from '../data/mockFinancialData';

const INFO_NOTE_OVERRIDES_STORAGE_KEY = 'valueBuddy.financialGridInfoNotes.v3';

type ProformaAdjustmentEdit = {
  mode: 'factor' | 'adjustment';
  draft?: string;
  factor?: number;
  adjustment?: number;
};

const DEFAULT_INFO_NOTE_TEXT: Record<string, string> = {
  'Proforma Balance Sheet': `This tab shows the projected financial position of the business in the future. It is not only historical data; it is calculated from projected income and balance sheet adjustments.

It answers:
- What the business will own (Assets)
- What the business will owe (Liabilities)
- What remains for the owner (Equity)

Input Sources (Documents + Sheet Tabs)
User Uploaded Documents (Primary Source)

Tax Returns:
Tax return documents are collected from the user for the last 3 years. These documents are processed to extract financial data from standard sections and pages based on the form type.

Data is extracted from source_section(s) such as:
"Form 1120" / "Form 1120-S" -> Income & Deductions sections
"Form 1065" -> Income and Expense sections
"Schedule C" -> Part I (Income) and Part II (Expenses)
"Schedule L" -> Balance Sheet (Assets, Liabilities, Equity)

From these sections, key values such as Revenue (Gross Receipts), Cost of Goods Sold, Operating Expenses, Net Income (final profit line), and Balance Sheet items like Assets, Liabilities, and Equity are captured and standardized.

Interim Financials:
Interim financial documents (monthly, quarterly, or YTD) are collected from the user and processed to extract financial data from standard financial statement sections.

Data is extracted from source_section(s) such as:
"Income Statement" / "Profit & Loss"
"Balance Sheet" / "Statement of Financial Position"

From these sections, key values such as current Revenue, Expenses, Net Income, and Balance Sheet items (Assets, Liabilities, Equity) are captured to reflect the most recent business performance and position.

These are first converted into structured financial data.

Sheet Tabs (Processed Data)
- BUSINESS BALANCE SHEET - base financial position
- COMMON ADJUSTMENTS - adjustments impacting values
- Projected Income Statement (Business P&L - Income Statement section) - net income added to equity
- CAPEX (if present) - affects asset values

Where this data is used
- Valuation Calculations -> used for equity value, net assets, and capital structure analysis
- Ratio Analysis -> used for liquidity ratios, leverage ratios, and financial stability metrics
- Working Capital Analysis -> used to evaluate current assets vs current liabilities
- Financial Projections -> used to project assets, liabilities, and overall financial position
- Income Statement Linkage -> retained earnings updated using net income
- Market Comparison (Comps) -> used to compare financial position and leverage with similar businesses`,
  'Projected Income Statement': `What is this tab

This tab represents the future earning performance of the business. It shows how the income statement is expected to look after applying adjustments and projections.

It provides a structured view of:
- Revenue - income generated by the business
- Expenses - costs incurred to run the business
- Profit - final earnings

Unlike a historical P&L, this is a forward-looking projected statement built using past financial data, normalized adjustments, and expected growth assumptions.

In simple terms:
It shows how much the business is expected to earn in the future based on current data and assumptions.

Input Sources (Documents + Sheet Tabs)
User Uploaded Documents (Primary Source)

Tax Returns:
Tax return documents are collected from the user for the last 3 years. These documents are processed to extract Income Statement (P&L) data from standard sections and pages based on the form type.

Data is extracted from source_section(s) such as:
"Form 1120" / "Form 1120-S" -> Income & Deductions sections
"Form 1065" -> Income and Expense sections
"Schedule C" -> Part I (Income) and Part II (Expenses)

From these sections, key values such as Revenue (Gross Receipts), Cost of Goods Sold, Operating Expenses, and Net Income (final profit line) are captured and standardized.

Interim Financials:
Interim financial documents (monthly, quarterly, or YTD) are collected from the user and processed to extract Income Statement (P&L) data from standard financial statement sections.

Data is extracted from source_section(s) such as:
"Income Statement"
"Profit & Loss"

From these sections, key values such as current Revenue, Expenses, and Net Income are captured to reflect the most recent business performance.

Sheet Tabs (Processed Data)
- BUSINESS P&L - base income data
- COMMON ADJUSTMENTS - normalization of income/expenses
- GROWTH (if present) - projection logic

Where this data is used
- Valuation Calculations -> used to derive EBITDA, net income, and earnings-based valuation
- Ratio Analysis -> used to calculate profit margins and performance ratios
- Weighted / Normalized Income -> used to compute adjusted and weighted earnings
- Financial Projections -> used as the base for future income forecasting
- Balance Sheet Linkage -> net income flows into equity (retained earnings)
- Market Comparison (Comps) -> used for benchmarking against similar businesses`
};

const Row = ({
  row,
  expandedRows,
  toggleRow,
  columns,
  level = 0,
  includedValues,
  onIncludedValueChange,
  isProforma,
  adjustmentEdits,
  onAdjustmentEditChange,
  projectedNetReceipts,
  onProjectedNetReceiptsChange
}: {
  row: FinancialRow, 
  expandedRows: Set<string>, 
  toggleRow: (id: string) => void,
  columns: YearColumn[],
  level?: number,
  includedValues: Record<string, string>,
  onIncludedValueChange: (id: string, value: string) => void,
  isProforma: boolean,
  adjustmentEdits: Record<string, ProformaAdjustmentEdit>,
  onAdjustmentEditChange: (id: string, mode: 'factor' | 'adjustment', value: string) => void,
  projectedNetReceipts: string,
  onProjectedNetReceiptsChange: (value: string) => void
}) => {
  const isExpanded = expandedRows.has(row.id);
  const hasChildren = row.children && row.children.length > 0;
  const isDocumentRow = level === 4;
  const isTotalLikeRow = row.name.toLowerCase().includes('total') || row.id === 'variance' || row.id === 'tangible-net-worth';
  const canEditProformaAdjustment = isProforma && !isTotalLikeRow;
  const adjustmentEditMode = adjustmentEdits[row.id]?.mode;

  const getRowStyle = () => {
    if (row.name.toLowerCase().includes('total') || row.name.toLowerCase().includes('net')) {
      return 'bg-emerald-50/10 font-bold text-gray-900 border-y border-gray-200';
    }
    if (level === 0) return 'bg-gray-50 font-semibold text-gray-900 border-y border-gray-200';
    if (level === 1) return 'bg-white font-medium text-gray-700 border-b border-gray-100';
    return 'bg-white font-normal text-gray-600 border-b border-gray-50';
  };

  return (
    <>
      <tr className={`transition-colors hover:bg-gray-50/50 ${getRowStyle()}`}>
        <td className={`py-2 px-4 sticky left-0 z-10 min-w-[200px] sm:min-w-[300px] border-r border-gray-100 ${level === 0 ? 'bg-gray-50' : 'bg-white'}`} style={{ paddingLeft: `${level * 20 + 16}px` }}>
          <div className="flex items-center gap-2">
            {isDocumentRow ? (
              <FileText className="w-3.5 h-3.5 text-gray-400" />
            ) : hasChildren ? (
              <button onClick={() => toggleRow(row.id)} className="p-1 hover:bg-gray-200/50 rounded transition-colors">
                {isExpanded ? <ChevronDown className="w-3.5 h-3.5 text-gray-500" /> : <ChevronRight className="w-3.5 h-3.5 text-gray-500" />}
              </button>
            ) : (
              <div className="w-5.5" />
            )}
            <span className="text-xs truncate">
              {row.name}
            </span>
          </div>
        </td>
        {columns.map((col) => {
          const val = row.values[col.year];
          const includedInValue = (row.values['included_in_value'] as string) || 'Yes';
          const isAdjustmentFactor = col.year === 'adjustment_factor';
          const isAdjustmentColumn = col.year === 'adjustment' || col.year === 'adjustment_factor' || col.year === 'adjustment_book_value';
          const isPercentage = col.year.includes('ratio') || col.year.includes('margin') || col.year.includes('cs');
          const isMetadataRow = row.id.startsWith('meta-');
          const isDays = row.id === 'meta-days';
          const isNumeric = typeof val === 'number';

          const hasEye = (row.id === 'doc-6' && (col.year === '2022' || col.year === '2023')) || 
                        (row.id === 'doc-3' && col.year === '2024');

          return (
            <td key={col.year} className={`py-2 px-4 text-right text-xs border-l border-gray-100 min-w-[120px] sm:min-w-[140px] ${isMetadataRow ? 'bg-gray-50/30 text-gray-500 italic' : ''}`}>
              <div className="flex items-center justify-end gap-1">
                {isProforma && col.year === 'included_in_value' ? (
                  <select 
                    value={includedInValue}
                    onChange={(e) => onIncludedValueChange(row.id, e.target.value)}
                    disabled={isTotalLikeRow}
                    className={`bg-white border border-gray-200 rounded px-2 py-1 text-[11px] font-semibold outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all w-full max-w-[70px] ${
                      isTotalLikeRow ? 'cursor-not-allowed opacity-60' : 'cursor-pointer hover:border-emerald-300'
                    }`}
                  >
                    <option value="Yes">Yes</option>
                    <option value="No">No</option>
                    <option value="-">-</option>
                  </select>
                ) : isProforma && (col.year === 'adjustment_factor' || col.year === 'adjustment') && canEditProformaAdjustment ? (
                  <input
                    type="number"
                    value={adjustmentEditMode === 'factor' && col.year === 'adjustment_factor'
                      ? adjustmentEdits[row.id]?.draft ?? ''
                      : adjustmentEditMode === 'adjustment' && col.year === 'adjustment'
                        ? adjustmentEdits[row.id]?.draft ?? ''
                        : typeof val === 'number'
                          ? Number(val.toFixed(2))
                          : ''}
                    onChange={(e) => onAdjustmentEditChange(row.id, col.year === 'adjustment_factor' ? 'factor' : 'adjustment', e.target.value)}
                    disabled={(col.year === 'adjustment_factor' && adjustmentEditMode === 'adjustment') || (col.year === 'adjustment' && adjustmentEditMode === 'factor')}
                    className="w-full max-w-[112px] rounded border border-gray-200 bg-white px-2 py-1 text-right text-[11px] font-semibold text-gray-700 outline-none transition-all focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 disabled:cursor-not-allowed disabled:bg-white disabled:text-gray-700 disabled:opacity-100"
                    step={col.year === 'adjustment_factor' ? '0.01' : '1'}
                    title={col.year === 'adjustment_factor' ? 'Edit adjustment factor percentage' : 'Edit adjustment amount'}
                  />
                ) : !isProforma && row.id === 'net-receipts' && col.year === 'projections' ? (
                  <input
                    type="number"
                    value={projectedNetReceipts}
                    onChange={(e) => onProjectedNetReceiptsChange(e.target.value)}
                    className="w-full max-w-[120px] rounded border border-gray-200 bg-white px-2 py-1 text-right text-[11px] font-semibold text-gray-700 outline-none transition-all focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20"
                    step="1"
                    title="Edit projected Net Receipts or Sales"
                  />
                ) : val === '-' || val === '' || (isNumeric && val === 0 && !isAdjustmentColumn) ? (
                  <span className="text-gray-300">-</span>
                ) : isNumeric ? (
                  <>
                    <span className={`${val === 0 && !isAdjustmentColumn ? 'text-gray-400' : ''}`}>
                      {isAdjustmentFactor ? `${(val as number).toFixed(0)}%` : isPercentage ? `${(val as number).toFixed(2)}%` : isDays ? val : `$${(val as number).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`}
                    </span>
                    {hasEye && <Eye className="w-3 h-3 text-emerald-400" />}
                  </>
                ) : (
                  <span className="text-gray-600">{val}</span>
                )}
              </div>
            </td>
          );
        })}
        <td className="py-2 px-4 text-right sticky right-0 bg-white z-10 w-10"></td>
      </tr>
      {isExpanded && hasChildren && row.children?.map(child => (
        <Row 
          key={child.id} 
          row={child} 
          expandedRows={expandedRows} 
          toggleRow={toggleRow} 
          columns={columns} 
          level={level + 1} 
          includedValues={includedValues}
          onIncludedValueChange={onIncludedValueChange}
          isProforma={isProforma}
          adjustmentEdits={adjustmentEdits}
          onAdjustmentEditChange={onAdjustmentEditChange}
          projectedNetReceipts={projectedNetReceipts}
          onProjectedNetReceiptsChange={onProjectedNetReceiptsChange}
        />
      ))}
    </>
  );
};

interface FinancialGridProps {
  onProjectedCommonSizingBasisChange?: (label: string) => void;
}

export const FinancialGrid = ({ onProjectedCommonSizingBasisChange }: FinancialGridProps) => {
  const [activeTab, setActiveTab] = useState('Proforma Balance Sheet');
  const [openInfoTab, setOpenInfoTab] = useState<string | null>(null);
  const [editingInfoTab, setEditingInfoTab] = useState<string | null>(null);
  const [infoNoteDrafts, setInfoNoteDrafts] = useState<Record<string, string>>({});
  const [infoNoteOverrides, setInfoNoteOverrides] = useState<Record<string, string>>(() => {
    if (typeof window === 'undefined') return {};
    try {
      return JSON.parse(window.localStorage.getItem(INFO_NOTE_OVERRIDES_STORAGE_KEY) || '{}');
    } catch {
      return {};
    }
  });
  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set(['assets-group', 'total-current-assets', 'cash-equivalents', 'inventory-group', 'liabilities-group', 'equity-group', 'revenue-group']));
  const [latestYear, setLatestYear] = useState('interim');
  const [includedValues, setIncludedValues] = useState<Record<string, string>>({});
  const [adjustmentEdits, setAdjustmentEdits] = useState<Record<string, ProformaAdjustmentEdit>>({});
  const commonSizingAverageBasis = 'all';
  const [projectedCommonSizingBasis, setProjectedCommonSizingBasis] = useState('cs_avg');
  const [projectedNetReceipts, setProjectedNetReceipts] = useState('2098300.64');
  const [ttmBaseYear, setTtmBaseYear] = useState('tr3');
  const [isDocumentPanelOpen, setIsDocumentPanelOpen] = useState(false);

  const isProforma = activeTab === 'Proforma Balance Sheet';
  const activeInfoTab = openInfoTab === activeTab ? activeTab : null;

  const commonSizingAverageOptions = [
    { value: 'historical', label: '2022-2024', columns: ['cs1', 'cs2', 'cs3'] },
    { value: 'historical_interim', label: '2022-2024 + Interim', columns: ['cs1', 'cs2', 'cs3', 'cs4'] },
    { value: 'all', label: 'All Columns', columns: ['cs1', 'cs2', 'cs3', 'cs4', 'cs5'] }
  ];

  const projectedCommonSizingOptions = [
    { value: 'cs1', label: '2022' },
    { value: 'cs2', label: '2023' },
    { value: 'cs3', label: '2024' },
    { value: 'cs4', label: 'Interim' },
    { value: 'cs5', label: 'Annualized' },
    { value: 'cs_avg', label: 'Average' }
  ];

  const ttmBaseYearOptions = [
    { value: 'tr1', label: '2022' },
    { value: 'tr2', label: '2023' },
    { value: 'tr3', label: '2024' }
  ];

  const handleIncludedValueChange = (id: string, value: string) => {
    setIncludedValues(prev => ({ ...prev, [id]: value }));
  };

  const handleAdjustmentEditChange = (id: string, mode: 'factor' | 'adjustment', value: string) => {
    setAdjustmentEdits(prev => {
      if (value === '') {
        const next = { ...prev };
        delete next[id];
        return next;
      }

      const numericValue = Number(value);
      if (Number.isNaN(numericValue)) {
        return {
          ...prev,
          [id]: { mode, draft: value }
        };
      }

      return {
        ...prev,
        [id]: mode === 'factor'
          ? { mode, factor: numericValue, draft: value }
          : { mode, adjustment: numericValue, draft: value }
      };
    });
  };

  const handleProjectedCommonSizingBasisChange = (value: string) => {
    setProjectedCommonSizingBasis(value);
    const selectedOption = projectedCommonSizingOptions.find(option => option.value === value);
    onProjectedCommonSizingBasisChange?.(selectedOption?.label ?? value);
  };

  const activeColumns = useMemo(() => {
    return isProforma ? PROFORMA_COLUMNS : INCOME_COLUMNS;
  }, [isProforma]);

  const activeData = useMemo(() => {
    return isProforma ? MOCK_DATA : INCOME_DATA;
  }, [isProforma]);

  // Recursively calculate adjustments for the Balance Sheet
  const enrichedData = useMemo(() => {
    if (!isProforma) {
      const averageNumericValues = (values: Record<string, string | number>, columns: string[]) => {
        const numericValues = columns
          .map(column => values[column])
          .filter((value): value is number => typeof value === 'number');

        if (numericValues.length === 0) return values.cs_avg ?? 0;
        return numericValues.reduce((sum, value) => sum + value, 0) / numericValues.length;
      };
      const commonSizingAverageColumns = commonSizingAverageOptions.find(option => option.value === commonSizingAverageBasis)?.columns ?? ['cs1', 'cs2', 'cs3', 'cs4', 'cs5'];

      const interimDays = 212;
      const ttmDaysByYear: Record<string, number> = { tr1: 365, tr2: 365, tr3: 366 };
      const remainingDays = 365 - interimDays;
      const calculateTtm = (values: Record<string, string | number>) => {
        const interimValue = values.interim;
        const selectedYearValue = values[ttmBaseYear];
        if (typeof interimValue !== 'number' || typeof selectedYearValue !== 'number') return values.ttm ?? 0;

        return interimValue + (selectedYearValue * remainingDays / (ttmDaysByYear[ttmBaseYear] || 365));
      };

      const projectedNetReceiptsValue = projectedNetReceipts.trim() === '' ? NaN : Number(projectedNetReceipts);
      const revenueRow = activeData.find(row => row.id === 'revenue-group');
      const revenueTtm = revenueRow ? calculateTtm(revenueRow.values) : 0;
      const revenueTtmValue = typeof revenueTtm === 'number' ? revenueTtm : 0;

      const processIncomeRow = (row: FinancialRow): FinancialRow => {
        const children = row.children?.map(processIncomeRow);
        const values = { ...row.values };
        const isMetadataRow = row.id.startsWith('meta-');

        if (!isMetadataRow) {
          if (row.id === 'net-receipts' && !Number.isNaN(projectedNetReceiptsValue)) {
            values.projections = projectedNetReceiptsValue;
          }

          values.cs_avg = averageNumericValues(values, commonSizingAverageColumns);
          values.cs6 = values[projectedCommonSizingBasis] ?? values.cs6;
          values.ttm = calculateTtm(values);

          if (typeof values.ttm === 'number' && revenueTtmValue !== 0) {
            values.ttm_cs = (values.ttm / revenueTtmValue) * 100;
          }
        }

        return {
          ...row,
          children,
          values
        };
      };

      return activeData.map(processIncomeRow);
    }

    const processRow = (row: FinancialRow): FinancialRow => {
      const incl = includedValues[row.id] || (row.values['included_in_value'] as string) || 'Yes';
      const lVal = (row.values[latestYear] as number) || 0;
      const manualEdit = adjustmentEdits[row.id];
      
      // Dynamic factor: Yes -> 0%, No -> 100%
      let currentFactorValue = incl === 'Yes' ? 0 : (incl === 'No' ? 100 : 0);
      
      let adjustment = 0;
      let children: FinancialRow[] = [];
      const rowIsTotalLike = row.name.toLowerCase().includes('total') || row.id === 'variance' || row.id === 'tangible-net-worth';

      if (row.children && row.children.length > 0) {
        children = row.children.map(processRow);
      }

      if (manualEdit?.mode === 'factor' && !rowIsTotalLike) {
        currentFactorValue = manualEdit.factor ?? currentFactorValue;
        adjustment = lVal * (currentFactorValue / 100) * -1;
      } else if (manualEdit?.mode === 'adjustment' && !rowIsTotalLike) {
        adjustment = manualEdit.adjustment ?? 0;
        currentFactorValue = lVal === 0 ? 0 : (adjustment / lVal) * -100;
      } else if (children.length > 0) {
        // Parent and total rows default to the sum of their children.
        adjustment = children.reduce((sum, child) => sum + (child.values['adjustment'] as number || 0), 0);
      } else {
        // Leaf row: logic
        if (incl === 'Yes') {
          // adjustment = ( latest Year x Factor value x (-1))
          adjustment = lVal * (currentFactorValue / 100) * -1;
        } else if (incl === 'No') {
          // adjustment = ( latest Year x (-1))
          adjustment = lVal * -1;
        } else {
          adjustment = 0;
        }
      }

      // Special handling for Variance row
      if (row.id === 'variance') {
        // This is a bit of a hack since we don't have global state here easily,
        // but for the mock it works if we assume the seed data's relative dependencies.
        // Actually, let's just use the seed's logic or sum up.
      }

      return {
        ...row,
        children: children.length > 0 ? children : undefined,
        values: {
          ...row.values,
          'included_in_value': incl,
          'adjustment_factor': currentFactorValue,
          'adjustment': adjustment,
          'adjustment_book_value': lVal + adjustment
        }
      };
    };

    let data = activeData.map(processRow);

    // After calculating all main groups, update Variance if it exists
    const assetsRow = data.find(r => r.id === 'assets-group');
    const liabRow = data.find(r => r.id === 'liabilities-group');
    const equityRow = data.find(r => r.id === 'equity-group');

    if (assetsRow && liabRow && equityRow) {
      const assetsAdj = assetsRow.values['adjustment'] as number || 0;
      const liabAdj = liabRow.values['adjustment'] as number || 0;
      const equityAdj = equityRow.values['adjustment'] as number || 0;
      
      data = data.map(r => {
        if (r.id === 'variance') {
          const adj = assetsAdj - (liabAdj + equityAdj);
          return {
            ...r,
            values: {
              ...r.values,
              'adjustment': adj,
              'adjustment_book_value': 0 // Variance book value is always 0
            }
          };
        }
        return r;
      });
    }

    return data;
  }, [activeData, isProforma, includedValues, adjustmentEdits, latestYear, commonSizingAverageBasis, projectedCommonSizingBasis, projectedNetReceipts, ttmBaseYear]);

  const toggleRow = (id: string) => {
    const newExpanded = new Set(expandedRows);
    if (newExpanded.has(id)) newExpanded.delete(id);
    else newExpanded.add(id);
    setExpandedRows(newExpanded);
  };

  const handleStartInfoNoteEdit = (tab: string) => {
    setInfoNoteDrafts(prev => ({ ...prev, [tab]: infoNoteOverrides[tab] ?? DEFAULT_INFO_NOTE_TEXT[tab] ?? '' }));
    setEditingInfoTab(tab);
  };

  const handleSaveInfoNoteEdit = (tab: string) => {
    const nextNote = infoNoteDrafts[tab] ?? '';
    setInfoNoteOverrides(prev => {
      const next = { ...prev, [tab]: nextNote };
      window.localStorage.setItem(INFO_NOTE_OVERRIDES_STORAGE_KEY, JSON.stringify(next));
      return next;
    });
    setEditingInfoTab(null);
  };

  const handleCancelInfoNoteEdit = (tab: string) => {
    setInfoNoteDrafts(prev => {
      const next = { ...prev };
      delete next[tab];
      return next;
    });
    setEditingInfoTab(null);
  };

  const renderSavedInfoNote = (note: string) => {
    if (!note) return <span>-</span>;

    const headingLabels = [
      'What is this tab',
      'It answers:',
      'Input Sources (Documents + Sheet Tabs)',
      'User Uploaded Documents (Primary Source)',
      'Tax Returns:',
      'Interim Financials:',
      'Sheet Tabs (Processed Data)',
      'Where this data is used',
      'In simple terms:'
    ];

    return note.split('\n').map((line, index) => {
      const trimmedLine = line.trim();
      const isHeading = headingLabels.includes(trimmedLine);
      const isBullet = trimmedLine.startsWith('- ');

      if (!trimmedLine) {
        return <div key={index} className="h-2" />;
      }

      if (isHeading) {
        return <p key={index} className="font-semibold text-gray-800">{trimmedLine}</p>;
      }

      if (isBullet) {
        return <p key={index} className="pl-4 text-gray-700">{trimmedLine}</p>;
      }

      return <p key={index} className="text-gray-700">{line}</p>;
    });
  };

  const renderInfoNoteContent = (tab: string, defaultContent: React.ReactNode) => {
    const isEditing = editingInfoTab === tab;
    const customNote = infoNoteOverrides[tab];

    if (isEditing) {
      return (
        <textarea
          value={infoNoteDrafts[tab] ?? DEFAULT_INFO_NOTE_TEXT[tab] ?? ''}
          onChange={(e) => setInfoNoteDrafts(prev => ({ ...prev, [tab]: e.target.value }))}
          className="h-full min-h-[56vh] w-full px-3 py-2 bg-white border border-emerald-100 rounded-lg text-[11px] sm:text-xs text-gray-700 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 resize-none leading-relaxed"
        />
      );
    }

    if (customNote !== undefined) {
      return (
        <div className="space-y-1 text-[11px] sm:text-xs leading-relaxed">
          {renderSavedInfoNote(customNote)}
        </div>
      );
    }

    return defaultContent;
  };


  return (
    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden flex flex-col h-full max-w-full shadow-sm">
      {/* Grid Toolbar */}
      <div className="p-3 border-b border-gray-100 bg-white">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-3 mb-2">
          <div className="flex items-center gap-1 p-1 bg-gray-100/50 rounded-xl overflow-x-auto no-scrollbar whitespace-nowrap">
            {['Proforma Balance Sheet', 'Projected Income Statement'].map(tab => (
              <div
                key={tab}
                className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold rounded-lg transition-all whitespace-nowrap ${
                  activeTab === tab ? 'bg-[#1e2d24] text-white shadow-md' : 'text-gray-500 hover:text-gray-700 hover:bg-white/50'
                }`}
              >
                <button
                  onClick={() => setActiveTab(tab)}
                  className="cursor-pointer"
                >
                  {tab}
                </button>
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    setActiveTab(tab);
                    setOpenInfoTab(prev => prev === tab ? null : tab);
                  }}
                  className={`p-0.5 rounded-full transition-colors ${
                    activeTab === tab
                      ? 'text-white/90 hover:bg-white/10'
                      : 'text-gray-500 hover:bg-gray-200'
                  }`}
                  aria-label={`Show ${tab} information`}
                  title="What this tab means and data flow"
                >
                  <Info className="w-3.5 h-3.5" />
                </button>
              </div>
            ))}
          </div>
          
          <div className="flex items-center gap-2 sm:gap-3 flex-wrap">
            <div className="hidden sm:flex items-center gap-2 px-4 py-2 bg-emerald-50 text-emerald-700 rounded-full border border-emerald-100 text-xs font-bold">
               <CheckCircle2 className="w-4 h-4" />
               All Items Classified
            </div>
            
            <div className="relative flex-1 sm:flex-none min-w-[140px]">
              <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
              <input 
                type="text" 
                placeholder="Search Statement..." 
                className="pl-10 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-lg text-xs w-full sm:w-56 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 transition-all"
              />
            </div>
            
            <button className="flex items-center gap-2 px-4 py-2 border border-gray-200 rounded-lg text-xs font-bold text-gray-700 hover:bg-gray-50 transition-colors shadow-sm">
              <Plus className="w-4 h-4 text-emerald-600" />
              <span className="hidden sm:inline">Add Year</span>
            </button>
            
            <div className="hidden sm:block h-6 w-[1px] bg-gray-200 mx-1" />
            
            <button
              onClick={() => setIsDocumentPanelOpen(prev => !prev)}
              className="flex items-center gap-2 px-4 py-2 border border-gray-200 rounded-lg text-xs font-bold text-gray-700 hover:bg-gray-50 transition-colors shadow-sm"
            >
              <Eye className="w-4 h-4 text-emerald-600" />
              <span className="hidden sm:inline">{isDocumentPanelOpen ? 'Hide Documents' : 'Show Documents'}</span>
            </button>
          </div>
        </div>

        {activeInfoTab === 'Proforma Balance Sheet' && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/40 p-4">
          <div
            role="dialog"
            aria-modal="true"
            aria-labelledby="proforma-balance-sheet-info-title"
            className="flex h-[82vh] w-full max-w-3xl flex-col overflow-hidden rounded-xl border border-emerald-100 bg-emerald-50 shadow-2xl"
          >
            <div className="flex shrink-0 items-center justify-between gap-2 border-b border-emerald-100 bg-emerald-50 px-3 py-3 sm:px-4">
              <div className="flex items-center gap-2">
                <Info className="w-4 h-4 text-emerald-700 shrink-0" />
                <p id="proforma-balance-sheet-info-title" className="text-xs sm:text-sm font-bold text-emerald-900">Proforma Balance Sheet</p>
              </div>
              <div className="flex items-center gap-1">
                {editingInfoTab === 'Proforma Balance Sheet' ? (
                  <>
                    <button
                      type="button"
                      onClick={() => handleSaveInfoNoteEdit('Proforma Balance Sheet')}
                      className="p-1 rounded-md text-emerald-700 hover:bg-emerald-100 transition-colors"
                      aria-label="Save Proforma Balance Sheet note"
                      title="Save note"
                    >
                      <Check className="w-3.5 h-3.5" />
                    </button>
                    <button
                      type="button"
                      onClick={() => handleCancelInfoNoteEdit('Proforma Balance Sheet')}
                      className="p-1 rounded-md text-emerald-700 hover:bg-emerald-100 transition-colors"
                      aria-label="Cancel Proforma Balance Sheet note edit"
                      title="Cancel"
                    >
                      <X className="w-3.5 h-3.5" />
                    </button>
                  </>
                ) : (
                  <button
                    type="button"
                    onClick={() => handleStartInfoNoteEdit('Proforma Balance Sheet')}
                    className="p-1 rounded-md text-emerald-700 hover:bg-emerald-100 transition-colors"
                    aria-label="Edit Proforma Balance Sheet note"
                    title="Edit note"
                  >
                    <Pencil className="w-3.5 h-3.5" />
                  </button>
                )}
                <button
                  type="button"
                  onClick={() => setOpenInfoTab(null)}
                  className="p-1 rounded-md text-emerald-700 hover:bg-emerald-100 transition-colors"
                  aria-label="Close tab information"
                  title="Close"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-3 sm:p-4">
            {renderInfoNoteContent('Proforma Balance Sheet', (
            <div className="space-y-2 text-[11px] sm:text-xs text-gray-700 leading-relaxed">
              <p>
                This tab shows the projected financial position of the business in the future. It is not only historical data;
                it is calculated from projected income and balance sheet adjustments.
              </p>
              <p className="font-semibold text-gray-800">It answers:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>What the business will own (Assets)</li>
                <li>What the business will owe (Liabilities)</li>
                <li>What remains for the owner (Equity)</li>
              </ul>

              <p className="font-semibold text-gray-800">Input Sources (Documents + Sheet Tabs)</p>
              <p className="font-semibold text-gray-800">User Uploaded Documents (Primary Source)</p>
              <ul className="list-disc pl-5 space-y-2">
  <li>
    <b>Tax Returns:</b> Tax return documents are collected from the user for the last 3 years. These documents are processed to extract financial data from standard sections and pages based on the form type. Data is extracted from source_section(s) such as:
    <br /><br />
    "Form 1120" / "Form 1120-S" → Income & Deductions sections<br />
    "Form 1065" → Income and Expense sections<br />
    "Schedule C" → Part I (Income) and Part II (Expenses)<br />
    "Schedule L" → Balance Sheet (Assets, Liabilities, Equity)
    <br /><br />
    From these sections, key values such as Revenue (Gross Receipts), Cost of Goods Sold, Operating Expenses, Net Income (final profit line), and Balance Sheet items like Assets, Liabilities, and Equity are captured and standardized.
  </li>

  <li>
    <b>Interim Financials:</b> Interim financial documents (monthly, quarterly, or YTD) are collected from the user and processed to extract financial data from standard financial statement sections. Data is extracted from source_section(s) such as:
    <br /><br />
    "Income Statement" / "Profit & Loss"<br />
    "Balance Sheet" / "Statement of Financial Position"
    <br /><br />
    From these sections, key values such as current Revenue, Expenses, Net Income, and Balance Sheet items (Assets, Liabilities, Equity) are captured to reflect the most recent business performance and position.
  </li>
</ul>
              <p>These are first converted into structured financial data.</p>

              <p className="font-semibold text-gray-800">Sheet Tabs (Processed Data)</p>
              <ul className="list-disc pl-5 space-y-1">
                <li><span className="font-semibold">BUSINESS BALANCE SHEET</span> - base financial position</li>
                <li><span className="font-semibold">COMMON ADJUSTMENTS</span> - adjustments impacting values</li>
                <li><span className="font-semibold">Projected Income Statement</span> (Business P&amp;L - Income Statement section) - net income added to equity</li>
                <li><span className="font-semibold">CAPEX</span> (if present) - affects asset values</li>
              </ul>

              <p className="font-semibold text-gray-800">Where this data is used</p>
              <ul className="list-disc pl-5 space-y-1">
                <li><span className="font-semibold">Valuation Calculations</span> - used for equity value, net assets, and capital structure analysis</li>
                <li><span className="font-semibold">Ratio Analysis</span> - used for liquidity ratios, leverage ratios, and financial stability metrics</li>
                <li><span className="font-semibold">Working Capital Analysis</span> - used to evaluate current assets vs current liabilities</li>
                <li><span className="font-semibold">Financial Projections</span> - used to project assets, liabilities, and overall financial position</li>
                <li><span className="font-semibold">Income Statement Linkage</span> - retained earnings updated using net income</li>
                <li><span className="font-semibold">Market Comparison (Comps)</span> - used to compare financial position and leverage with similar businesses</li>
              </ul>
            </div>
            ))}
            </div>
          </div>
          </div>
        )}

        {activeInfoTab === 'Projected Income Statement' && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/40 p-4">
          <div
            role="dialog"
            aria-modal="true"
            aria-labelledby="projected-income-statement-info-title"
            className="flex h-[82vh] w-full max-w-3xl flex-col overflow-hidden rounded-xl border border-emerald-100 bg-emerald-50 shadow-2xl"
          >
            <div className="flex shrink-0 items-center justify-between gap-2 border-b border-emerald-100 bg-emerald-50 px-3 py-3 sm:px-4">
              <div className="flex items-center gap-2">
                <Info className="w-4 h-4 text-emerald-700 shrink-0" />
                <p id="projected-income-statement-info-title" className="text-xs sm:text-sm font-bold text-emerald-900">Projected Income Statement</p>
              </div>
              <div className="flex items-center gap-1">
                {editingInfoTab === 'Projected Income Statement' ? (
                  <>
                    <button
                      type="button"
                      onClick={() => handleSaveInfoNoteEdit('Projected Income Statement')}
                      className="p-1 rounded-md text-emerald-700 hover:bg-emerald-100 transition-colors"
                      aria-label="Save Projected Income Statement note"
                      title="Save note"
                    >
                      <Check className="w-3.5 h-3.5" />
                    </button>
                    <button
                      type="button"
                      onClick={() => handleCancelInfoNoteEdit('Projected Income Statement')}
                      className="p-1 rounded-md text-emerald-700 hover:bg-emerald-100 transition-colors"
                      aria-label="Cancel Projected Income Statement note edit"
                      title="Cancel"
                    >
                      <X className="w-3.5 h-3.5" />
                    </button>
                  </>
                ) : (
                  <button
                    type="button"
                    onClick={() => handleStartInfoNoteEdit('Projected Income Statement')}
                    className="p-1 rounded-md text-emerald-700 hover:bg-emerald-100 transition-colors"
                    aria-label="Edit Projected Income Statement note"
                    title="Edit note"
                  >
                    <Pencil className="w-3.5 h-3.5" />
                  </button>
                )}
                <button
                  type="button"
                  onClick={() => setOpenInfoTab(null)}
                  className="p-1 rounded-md text-emerald-700 hover:bg-emerald-100 transition-colors"
                  aria-label="Close tab information"
                  title="Close"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>

            <div className="flex-1 overflow-y-auto p-3 sm:p-4">
            {renderInfoNoteContent('Projected Income Statement', (
            <div className="space-y-2 text-[11px] sm:text-xs text-gray-700 leading-relaxed">
              <p className="font-semibold text-gray-800">What is this tab</p>
              <p>
                This tab represents the future earning performance of the business. It shows how the income statement is
                expected to look after applying adjustments and projections.
              </p>
              <p>It provides a structured view of:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li><span className="font-semibold">Revenue</span> - income generated by the business</li>
                <li><span className="font-semibold">Expenses</span> - costs incurred to run the business</li>
                <li><span className="font-semibold">Profit</span> (Net Income) - final earnings</li>
              </ul>
              <p>
                Unlike a historical P&amp;L, this is a forward-looking projected statement built using past financial data,
                normalized adjustments, and expected growth assumptions.
              </p>
              <p>
                <span className="font-semibold text-gray-800">In simple terms:</span> It shows how much the business is
                expected to earn in the future based on current data and assumptions.
              </p>

              <p className="font-semibold text-gray-800">Input Sources (Documents + Sheet Tabs)</p>
              <p className="font-semibold text-gray-800">User Uploaded Documents (Primary Source)</p>
              <ul className="list-disc pl-5 space-y-2">
  <li>
    <b>Tax Returns:</b> Tax return documents are collected from the user for the last 3 years. These documents are processed to extract Income Statement (P&L) data from standard sections and pages based on the form type. Data is extracted from source_section(s) such as:
    <br /><br />
    "Form 1120" / "Form 1120-S" → Income & Deductions sections<br />
    "Form 1065" → Income and Expense sections<br />
    "Schedule C" → Part I (Income) and Part II (Expenses)
    <br /><br />
    From these sections, key values such as Revenue (Gross Receipts), Cost of Goods Sold, Operating Expenses, and Net Income (final profit line) are captured and standardized.
  </li>

  <li>
    <b>Interim Financials:</b> Interim financial documents (monthly, quarterly, or YTD) are collected from the user and processed to extract Income Statement (P&L) data from standard financial statement sections. Data is extracted from source_section(s) such as:
    <br /><br />
    "Income Statement"<br />
    "Profit & Loss"
    <br /><br />
    From these sections, key values such as current Revenue, Expenses, and Net Income are captured to reflect the most recent business performance.
  </li>
</ul>

              <p className="font-semibold text-gray-800">Sheet Tabs (Processed Data)</p>
              <ul className="list-disc pl-5 space-y-1">
                <li><span className="font-semibold">BUSINESS P&amp;L</span> - base income data</li>
                <li><span className="font-semibold">COMMON ADJUSTMENTS</span> - normalization of income/expenses</li>
                <li><span className="font-semibold">GROWTH</span> (if present) - projection logic</li>
              </ul>

              <p className="font-semibold text-gray-800">Where this data is used</p>
              <ul className="list-disc pl-5 space-y-1">
                <li><span className="font-semibold">Valuation Calculations</span> - used to derive EBITDA, net income, and earnings-based valuation</li>
                <li><span className="font-semibold">Ratio Analysis</span> - used to calculate profit margins and performance ratios</li>
                <li><span className="font-semibold">Weighted / Normalized Income</span> - used to compute adjusted and weighted earnings</li>
                <li><span className="font-semibold">Financial Projections</span> - used as the base for future income forecasting</li>
                <li><span className="font-semibold">Balance Sheet Linkage</span> - net income flows into equity (retained earnings)</li>
                <li><span className="font-semibold">Market Comparison (Comps)</span> - used for benchmarking against similar businesses</li>
              </ul>
            </div>
            ))}
            </div>
          </div>
          </div>
        )}

        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
           <div className="flex items-center gap-2 text-xs text-gray-500 font-medium">
              <span className="flex items-center gap-1.5 py-1 px-2 bg-gray-100 rounded text-gray-700"><FileText className="w-3.5 h-3.5" /> Business</span>
              <ChevronRight className="w-3.5 h-3.5 text-gray-300" />
              <span className="text-emerald-600 font-bold bg-emerald-50 px-2 py-0.5 rounded">Accept</span>
           </div>
           
           <div className="flex flex-col sm:flex-row sm:items-center gap-3">
              <span className="text-xs text-gray-400 font-medium italic">Last saved • <span className="text-gray-600 font-bold">Apr 22, 2026, 2:34 PM</span></span>
              <div className="flex items-center gap-2">
                 <button className="flex items-center gap-2 px-3 py-1.5 text-xs font-bold text-gray-600 hover:bg-gray-100 rounded-lg transition-all">
                    <Eye className="w-4 h-4 text-emerald-500" /> Scenario
                 </button>
                 <button className="flex items-center gap-2 px-4 py-1.5 bg-[#1e2d24] text-white text-xs font-bold rounded-lg shadow-lg hover:bg-[#2a433a] transition-all">
                    <Save className="w-4 h-4" /> Save
                 </button>
                 <button className="flex items-center gap-2 px-3 py-1.5 text-xs font-bold text-gray-600 hover:bg-gray-100 rounded-lg transition-all">
                    <RefreshCw className="w-4 h-4 text-emerald-500" /> Refresh
                 </button>
              </div>
           </div>
        </div>
      </div>

      {/* Grid + Document Container */}
      <div className="flex-1 min-h-0 flex overflow-hidden relative">
        <div className="flex-1 overflow-auto relative">
          <table className="w-full border-collapse text-left min-w-full">
          <thead className="sticky top-0 z-20 shadow-sm">
            <tr className="bg-gray-50 text-gray-700">
              <th className="py-3 px-4 font-bold text-xs min-w-[200px] sm:min-w-[300px] sticky left-0 bg-gray-50 z-30 border-r border-gray-200 uppercase tracking-wider">
                Statement Type
              </th>
              {activeColumns.map(col => (
                <th key={col.year} className="py-3 px-4 min-w-[120px] sm:min-w-[140px] border-l border-gray-200">
                  <div className="flex flex-col gap-1">
                    <div className="flex items-center justify-between gap-2">
                      <span className="text-xs font-bold uppercase tracking-wider whitespace-nowrap">{col.label || col.year}</span>
                      {isProforma && col.year === 'adjustment' && (
                        <select 
                          value={latestYear}
                          onChange={(e) => setLatestYear(e.target.value)}
                          className="bg-white border border-gray-200 rounded px-2 py-1 text-[10px] normal-case font-bold outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 cursor-pointer shadow-sm transition-all hover:border-emerald-300"
                        >
                          <option value="tax_return_1">Tax Return (2022)</option>
                          <option value="tax_return_2">Tax Return (2023)</option>
                          <option value="tax_return_3">Tax Return (2024)</option>
                          <option value="interim">Interim (2025)</option>
                        </select>
                      )}
                      {!isProforma && col.year === 'cs6' && (
                        <select
                          value={projectedCommonSizingBasis}
                          onChange={(e) => handleProjectedCommonSizingBasisChange(e.target.value)}
                          className="bg-white border border-gray-200 rounded px-2 py-1 text-[10px] normal-case font-bold outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 cursor-pointer shadow-sm transition-all hover:border-emerald-300 max-w-[110px]"
                          title="Select columns for projected common sizing"
                        >
                          {projectedCommonSizingOptions.map(option => (
                            <option key={option.value} value={option.value}>{option.label}</option>
                          ))}
                        </select>
                      )}
                      {!isProforma && col.year === 'ttm' && (
                        <select
                          value={ttmBaseYear}
                          onChange={(e) => setTtmBaseYear(e.target.value)}
                          className="bg-white border border-gray-200 rounded px-2 py-1 text-[10px] normal-case font-bold outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500 cursor-pointer shadow-sm transition-all hover:border-emerald-300"
                          title="Select year for prorated TTM data"
                        >
                          {ttmBaseYearOptions.map(option => (
                            <option key={option.value} value={option.value}>{option.label}</option>
                          ))}
                        </select>
                      )}
                    </div>
                    <span className="text-[10px] font-medium text-gray-400 uppercase">{col.period}</span>
                  </div>
                </th>
              ))}
              <th className="w-10 sticky right-0 bg-gray-50 border-l border-gray-200"></th>
            </tr>
          </thead>
          <tbody className="bg-white">
            {enrichedData.map(row => (
              <Row 
                key={row.id} 
                row={row} 
                expandedRows={expandedRows} 
                toggleRow={toggleRow} 
                columns={activeColumns} 
                includedValues={includedValues}
                onIncludedValueChange={handleIncludedValueChange}
                isProforma={isProforma}
                adjustmentEdits={adjustmentEdits}
                onAdjustmentEditChange={handleAdjustmentEditChange}
                projectedNetReceipts={projectedNetReceipts}
                onProjectedNetReceiptsChange={setProjectedNetReceipts}
              />
            ))}
            {/* Fill space */}
            {[...Array(3)].map((_, i) => (
              <tr key={i} className="border-b border-gray-100/50">
                <td className="py-4 px-4 sticky left-0 bg-white z-10 border-r border-gray-100 shadow-[2px_0_5px_-2px_rgba(0,0,0,0.05)]"></td>
                {activeColumns.map(col => <td key={col.year} className="py-4 px-4 border-l border-gray-100"></td>)}
                <td className="w-10 sticky right-0 bg-white z-10 border-l border-gray-100"></td>
              </tr>
            ))}
          </tbody>
          </table>
        </div>

      <div
        className={`shrink-0 bg-white shadow-2xl transition-all duration-300 ease-out overflow-hidden ${
          isDocumentPanelOpen ? 'w-full sm:w-[520px] lg:w-[620px] border-l border-gray-200' : 'w-0 border-l-0'
        }`}
      >
        <div className="h-full flex flex-col bg-gray-100">
          <div className="h-12 px-4 bg-white border-b border-gray-200 flex items-center justify-between shrink-0">
            <div>
              <p className="text-xs font-bold text-[#1e2d24]">202ba8cfc156-MAJESTICNAILSSPALLC2022.pdf</p>
              <p className="text-[10px] text-gray-400 font-medium">Demo document preview</p>
            </div>
            <button
              onClick={() => setIsDocumentPanelOpen(false)}
              className="w-7 h-7 rounded-full border border-gray-200 text-gray-500 hover:bg-gray-50 hover:text-gray-900 transition-colors"
              aria-label="Hide documents"
            >
              ×
            </button>
          </div>

          <div className="h-11 px-4 bg-white border-b border-gray-200 flex items-center justify-between shrink-0">
            <div className="flex items-center gap-2 text-xs text-gray-500">
              <button className="px-2 py-1 rounded hover:bg-gray-100">|‹</button>
              <button className="px-2 py-1 rounded hover:bg-gray-100">‹</button>
              <button className="px-2 py-1 rounded hover:bg-gray-100">›</button>
              <button className="px-2 py-1 rounded hover:bg-gray-100">›|</button>
              <span className="ml-2 px-3 py-1 border border-gray-200 rounded bg-white text-gray-900 font-bold">1</span>
              <span>of 42</span>
            </div>
            <div className="flex items-center gap-3 text-xs text-gray-600">
              <button className="w-7 h-7 rounded-full border border-gray-200 hover:bg-gray-50 font-bold">−</button>
              <button className="w-7 h-7 rounded-full border border-gray-200 hover:bg-gray-50 font-bold">+</button>
              <span className="font-bold">53%</span>
            </div>
          </div>

          <div className="flex-1 overflow-auto p-6">
            <div className="mx-auto w-[360px] min-h-[520px] bg-white shadow-lg border border-gray-200 flex flex-col items-center justify-center text-center p-10">
              <p className="text-[10px] font-bold text-gray-700 uppercase">2022 S-Corporation Return</p>
              <p className="text-[9px] text-gray-500 mt-1">Prepared for</p>
              <p className="text-[11px] font-black text-gray-900 mt-2">MAJESTIC NAILS & SPA LLC</p>
              <p className="text-[10px] text-gray-600">650 SHELBYVILLE ROAD</p>
              <p className="text-[10px] text-gray-600">LOUISVILLE, KY 40223</p>
              <div className="mt-28">
                <p className="text-[10px] font-bold text-gray-800">YOUNG W. PAK, CPA PSC</p>
                <p className="text-[9px] text-gray-500">1300 CLEAR SPRINGS TRACE STE 3</p>
                <p className="text-[9px] text-gray-500">LOUISVILLE, KY 40223</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  );
};
